### PR TITLE
Bugfix for listing filters with stash v0.23.1

### PR DESCRIPTION
**Pull request by mrbokster**
This might not be a full fix for all changes and errors, its just what made it work for me and my filters. The filter property in the response is deprecated and split in two so there might be other issues in other parts of the plugin.

### CODE REVIEW

**Comment by gitgiggety** [comment]
Thank you @mrbokster . There was just an issue with exclusions (especially when applying both an include and an exclude filter) which I fixed as well.

**Comment by mrbokster** [comment]
It crashes for me again with 0.0.8,

Seems to be in criterion_parser.py

        if 'items' in value:
            filter['value'] = list(map(lambda v: v['id'], value['items']))

needs to be something like:
        if 'items' in value and value['items'] is not None:
            filter['value'] = list(map(lambda v: v['id'], value['items']))

But done in proper python, this just makes it work for me.

The filter in question that crashes:
{'modifier': 'INCLUDES', 'value': {'depth': 0, 'excluded': [{'id': 813, 'label': 'Animated'}, {'id': 1315, 'label': 'Cock Hero'}, {'id': 496, 'label': 'Movies'}, {'id': 1034, 'label': 'PMV'}, {'id': 1316, 'label': 'Stim'}, {'id': 497, 'label': 'Compilation'}], 'items': None}}

I think thats what you tried to fix with your edit but this still crashes at the moment.

**Comment by mrbokster** [comment]
Also noticed an error in another place with this release.

stash_interface.py crashes due to a change in how the StashIDCriterionInput has changed.
For something like:
```
    "scene_filter": {
        "stash_id_endpoint": {
            "modifier": "IS_NULL",
            "value": ""
        }
    }
```

`value` is not longer valid and needs to be `stash_id` instead.

It started working for me after changing tag_item.py but studio_item.py also has it but unsure if its an issue there.
            `criterion = {self._filter_name: {'modifier': 'INCLUDES_ALL', 'stash_id': [tag['id']]}}`

**Comment by mrbokster** [comment]
Im gonna open another PR instead of typing here, figured out how to fix but its most likely bad python.

**Pull request merged**
